### ISSUE TITLE
Expand GH Actions

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHPCSUtils#240]
From #239:

In the future additional workflows/jobs could be added to, for instance,
- [ ] Check for broken links in the documentation site every month.
- [x] Check the markdown files for style, spelling and broken links. #312
- [x] Check Yaml files for style and formating. #313
- [x] Automatically update the documentation site. #419
- [x] Run the tests with non-required PHP extensions (`iconv`, `mbstring`) disabled. #316
